[운영체제] 스케줄러 - 발표 자료 추가
dev-splin/fake-developer-CS-study pull request #3
Opened 2021-06-20 14:21 UTC by ArtistDeveloper

Scheduler 발표 자료 추가 및 질문에 대한 답변 내용 추가

2021-06-20 14:40 UTC, dev-splin requested changes
리뷰 참고해서 수정 후 다시 PR 부탁드립니다!

2021-06-20 14:40 UTC, dev-splin commented on OS/Scheduler.md
> +1. 프로세스가 생성되어 실행될 때 필요한 시스템의 여러자원을 해당 프로세스에게 할당하는 작업을 의미
스케쥴링은 어느 프로세스가 CPU를 선점하여 사용할지 결정하는 작업 아닐까요??
적어주신 내용은 스케쥴링보다는 프로세스 설명과 유사하다고 생각됩니다..!!

2021-06-20 14:40 UTC, dev-splin commented on OS/Scheduler.md
> +- 작업 스케줄러라도 불리는 이것은 어떤 프로세스를 Readuy Queue에 삽입할지를 결정하는 역할을 한다.
오타있습니다! 스케줄러라도!

2021-06-20 14:51 UTC, ArtistDeveloper commented on OS/Scheduler.md
> +1. 프로세스가 생성되어 실행될 때 필요한 시스템의 여러자원을 해당 프로세스에게 할당하는 작업을 의미
"시스템의 여러자원을 프로세스에게 할당하는 작업"과 "스케쥴링은 어느 프로세스가 CPU를 선점하여 사용할지 결정하는 작업"은 같은 의미라고 느껴지는데 혹시 다른 걸까여?? 저는 둘다 스케줄링의 설명으로 보여서 ㅠㅠ.. 혹시 조금 더 설명부탁드릴 수 있을까요?

2021-06-21 09:39 UTC, dev-splin commented on OS/Scheduler.md
> +1. 프로세스가 생성되어 실행될 때 필요한 시스템의 여러자원을 해당 프로세스에게 할당하는 작업을 의미
제가 생각하기에는 스케줄링의 초점이 "자원의 할당" 보다는 "조율" 하는 쪽에 더 가깝다고 생각되어서요!!

2021-06-21 09:39 UTC, dev-splin commented on OS/Scheduler.md
> +1. 프로세스가 생성되어 실행될 때 필요한 시스템의 여러자원을 해당 프로세스에게 할당하는 작업을 의미
스네이크님 발표 자료에 보면
프로세스 ⇒ 운영체제로부터 자원( 프로세서, 필요한 주소 공간, 메모리 )을 할당받는 작업의 단위
라고 되어있는 것을 볼 수 있습니다!

2021-06-21 09:39 UTC, dev-splin commented on OS/Scheduler.md
> +1. 프로세스가 생성되어 실행될 때 필요한 시스템의 여러자원을 해당 프로세스에게 할당하는 작업을 의미
이미 자원은 프로세스가 생성되면서 할당받았고, 그 프로세스가 CPU를 선점하면서 실행하게 되는데, 이 때 프로세스들이 어떤 조건으로 CPU를 선점하게 하는지 관리, 조율해주는 것을 스케줄러라고 저는 생각하고 있습니다!

2021-06-21 11:30 UTC, dev-splin approved these changes
추가로 정리하시느라 고생많으셨습니다..!!

2021-06-21 11:30 UTC, merged